# Default Jekyll build configuration, used by GitHub.

markdown:   redcarpet
pygments:   true

baseurl:    ''

name:  Rob McGuire-Dale

resume:
    names:
        - Alice
        - Bob
        - Charlie
