# Jekyll configuration and data


# Jekyll config
# -------------
encoding:   UTF-8
markdown:   redcarpet
pygments:   true
baseurl:    ''
permalink:  /blog/:title.html


# Global
# ------
name:           Rob McGuire-Dale
img_base_url:   https://googledrive.com/host/0B9Ek2mpacQQMMUVYaklQMmJsZkE/website/
