# Default Jekyll build configuration, used by GitHub.

markdown:   redcarpet
pygments:   true

baseurl:    ''

name:       Rob M.D.
long_name:  Rob McGuire-Dale
# name:       Spc NdHvjsf-Ebmf
# short_name: Spc N.E.

resume:
    names:
        - Alice
        - Bob
        - Charlie
